use anyhow::Result;
use sqlx::{
    sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions},
    SqlitePool,
};
use std::str::FromStr;

pub async fn make_pool(database_url: &str) -> Result<SqlitePool> {
    let opts = SqliteConnectOptions::from_str(database_url)?
        .create_if_missing(true)
        .foreign_keys(true)
        .journal_mode(SqliteJournalMode::Wal)
        .busy_timeout(std::time::Duration::from_secs(5));

    let pool = SqlitePoolOptions::new()
        .max_connections(5)
        .connect_with(opts)
        .await?;

    // Run migrations at startup
    //sqlx::migrate!("./migrations").run(&pool).await?;

    Ok(pool)
}

pub async fn create_tables(pool: &SqlitePool) -> Result<()> {
    let statements = [
        r#"
        CREATE TABLE IF NOT EXISTS racecards (
            id INTEGER PRIMARY KEY,
            zip_file_name TEXT NOT NULL,
            track TEXT NOT NULL,
            date TEXT NOT NULL,
            long_date TEXT NOT NULL
        );
        "#,
        r#"
        CREATE TABLE IF NOT EXISTS races (
            id INTEGER PRIMARY KEY,
            racecard_id INTEGER NOT NULL,
            race_number INTEGER,
            distance INTEGER,
            surface TEXT NOT NULL,
            race_type TEXT NOT NULL,
            age_sex_restrictions TEXT NOT NULL,
            todays_race_classification TEXT NOT NULL,
            purse INTEGER,
            claiming_price INTEGER,
            track_record REAL,
            race_conditions TEXT NOT NULL,
            todays_lasix_list TEXT NOT NULL,
            todays_bute_list TEXT NOT NULL,
            todays_coupled_list TEXT NOT NULL,
            todays_mutuel_list TEXT NOT NULL,
            simulcast_host_track_code TEXT NOT NULL,
            simulcast_host_track_race_number INTEGER,
            all_weather_surface_flag TEXT NOT NULL,
            race_conditions_line1 TEXT NOT NULL,
            race_conditions_line2 TEXT NOT NULL,
            race_conditions_line3 TEXT NOT NULL,
            race_conditions_line4 TEXT NOT NULL,
            race_conditions_line5 TEXT NOT NULL,
            race_conditions_line6 TEXT NOT NULL,
            low_claiming_price INTEGER,
            statebred_flag TEXT NOT NULL,
            wager_type_line1 TEXT NOT NULL,
            wager_type_line2 TEXT NOT NULL,
            wager_type_line3 TEXT NOT NULL,
            wager_type_line4 TEXT NOT NULL,
            wager_type_line5 TEXT NOT NULL,
            wager_type_line6 TEXT NOT NULL,
            wager_type_line7 TEXT NOT NULL,
            wager_type_line8 TEXT NOT NULL,
            wager_type_line9 TEXT NOT NULL,
            two_f_bris_pace_par INTEGER,
            four_f_bris_pace_par INTEGER,
            six_f_bris_pace_par INTEGER,
            bris_speed_for_class INTEGER,
            bris_late_pace_par INTEGER,
            post_times TEXT NOT NULL,
            post_time_pacific_military TEXT NOT NULL,
            todays_equibase_abbreviated_race_conditions TEXT NOT NULL,
            FOREIGN KEY (racecard_id) REFERENCES racecards(id) ON DELETE CASCADE
        );
        "#,
        r#"
        CREATE TABLE IF NOT EXISTS horses (
            id INTEGER PRIMARY KEY,
            race_id INTEGER NOT NULL,
            post_position INTEGER,
            entry TEXT NOT NULL,
            claiming_price_of_horse INTEGER,
            breed_type TEXT NOT NULL,
            todays_nasal_strip_change INTEGER,
            todays_trainer TEXT NOT NULL,
            trainer_starts INTEGER,
            trainer_wins INTEGER,
            trainer_places INTEGER,
            trainer_shows INTEGER,
            todays_jockey TEXT NOT NULL,
            apprentice_weight_allowance INTEGER,
            jockey_starts INTEGER,
            jockey_wins INTEGER,
            jockey_places INTEGER,
            jockey_shows INTEGER,
            todays_owner TEXT NOT NULL,
            owners_silks TEXT NOT NULL,
            main_track_only_ae_indicator TEXT NOT NULL,
            program_number TEXT NOT NULL,
            morning_line_odds REAL,
            horse_name TEXT NOT NULL,
            year_of_birth INTEGER,
            horses_foaling_month INTEGER,
            sex TEXT NOT NULL,
            horses_color TEXT NOT NULL,
            weight INTEGER,
            sire TEXT NOT NULL,
            sires_sire TEXT NOT NULL,
            dam TEXT NOT NULL,
            dams_sire TEXT NOT NULL,
            breeder TEXT NOT NULL,
            state_country_where_bred TEXT NOT NULL,
            program_post_position TEXT NOT NULL,
            todays_medication_new INTEGER,
            todays_medication_old INTEGER,
            equipment_change INTEGER,
            lifetime_record_todays_distance_starts INTEGER,
            lifetime_record_todays_distance_wins INTEGER,
            lifetime_record_todays_distance_places INTEGER,
            lifetime_record_todays_distance_shows INTEGER,
            lifetime_record_todays_distance_earnings INTEGER,
            lifetime_record_todays_track_starts INTEGER,
            lifetime_record_todays_track_wins INTEGER,
            lifetime_record_todays_track_places INTEGER,
            lifetime_record_todays_track_shows INTEGER,
            lifetime_record_todays_track_earnings INTEGER,
            lifetime_record_turf_starts INTEGER,
            lifetime_record_turf_wins INTEGER,
            lifetime_record_turf_places INTEGER,
            lifetime_record_turf_shows INTEGER,
            lifetime_record_turf_earnings INTEGER,
            lifetime_record_wet_starts INTEGER,
            lifetime_record_wet_wins INTEGER,
            lifetime_record_wet_places INTEGER,
            lifetime_record_wet_shows INTEGER,
            lifetime_record_wet_earnings INTEGER,
            current_year_record_year INTEGER,
            current_year_record_starts INTEGER,
            current_year_record_wins INTEGER,
            current_year_record_places INTEGER,
            current_year_record_shows INTEGER,
            current_year_record_earnings INTEGER,
            previous_year_record_year INTEGER,
            previous_year_record_starts INTEGER,
            previous_year_record_wins INTEGER,
            previous_year_record_places INTEGER,
            previous_year_record_shows INTEGER,
            previous_year_record_earnings INTEGER,
            lifetime_record_starts INTEGER,
            lifetime_record_wins INTEGER,
            lifetime_record_places INTEGER,
            lifetime_record_shows INTEGER,
            lifetime_record_earnings INTEGER,
            bris_run_style TEXT NOT NULL,
            quirin_speed_points INTEGER,
            trainer_jockey_combo_starts INTEGER,
            trainer_jockey_combo_wins INTEGER,
            trainer_jockey_combo_places INTEGER,
            trainer_jockey_combo_shows INTEGER,
            trainer_jockey_combo_roi REAL,
            days_since_last_race INTEGER,
            lifetime_all_weather_starts INTEGER,
            lifetime_all_weather_wins INTEGER,
            lifetime_all_weather_places INTEGER,
            lifetime_all_weather_shows INTEGER,
            lifetime_all_weather_earnings INTEGER,
            best_bris_speed_all_weather_surface INTEGER,
            bris_prime_power_rating REAL,
            trainer_starts_current_year INTEGER,
            trainer_wins_current_year INTEGER,
            trainer_places_current_year INTEGER,
            trainer_shows_current_year INTEGER,
            trainer_roi_current_year REAL,
            trainer_starts_previous_year INTEGER,
            trainer_wins_previous_year INTEGER,
            trainer_places_previous_year INTEGER,
            trainer_shows_previous_year INTEGER,
            trainer_roi_previous_year REAL,
            jockey_starts_current_year INTEGER,
            jockey_wins_current_year INTEGER,
            jockey_places_current_year INTEGER,
            jockey_shows_current_year INTEGER,
            jockey_roi_current_year REAL,
            jockey_starts_previous_year INTEGER,
            jockey_wins_previous_year INTEGER,
            jockey_places_previous_year INTEGER,
            jockey_shows_previous_year INTEGER,
            jockey_roi_previous_year REAL,
            sire_stud_fee INTEGER,
            best_bris_speed_fast_track INTEGER,
            best_bris_speed_turf INTEGER,
            best_bris_speed_off_track INTEGER,
            best_bris_speed_distance INTEGER,
            auction_price INTEGER,
            where_when_sold_at_auction TEXT NOT NULL,
            bris_dirt_pedigree_rating TEXT NOT NULL,
            bris_mud_pedigree_rating TEXT NOT NULL,
            bris_turf_pedigree_rating TEXT NOT NULL,
            bris_distance_pedigree_rating TEXT NOT NULL,
            best_bris_speed_life INTEGER,
            best_bris_speed_most_recent_year INTEGER,
            best_bris_speed_2nd_most_recent_year INTEGER,
            best_bris_speed_todays_track INTEGER,
            starts_fast_dirt INTEGER,
            wins_fast_dirt INTEGER,
            places_fast_dirt INTEGER,
            shows_fast_dirt INTEGER,
            earnings_fast_dirt INTEGER,
            jockey_distance_turf_label TEXT NOT NULL,
            jockey_distance_turf_starts INTEGER,
            jockey_distance_turf_wins INTEGER,
            jockey_distance_turf_places INTEGER,
            jockey_distance_turf_shows INTEGER,
            jockey_distance_turf_roi REAL,
            jockey_distance_turf_earnings INTEGER,
            trainer_jockey_combo_starts_meet INTEGER,
            trainer_jockey_combo_wins_meet INTEGER,
            trainer_jockey_combo_places_meet INTEGER,
            trainer_jockey_combo_shows_meet INTEGER,
            trainer_jockey_combo_roi_meet REAL,
            note TEXT NOT NULL,
            FOREIGN KEY (race_id) REFERENCES races(id) ON DELETE CASCADE
        );
        "#,
        r#"
        CREATE TABLE IF NOT EXISTS workouts (
            id INTEGER PRIMARY KEY,
            horse_id INTEGER NOT NULL,
            date TEXT NOT NULL,
            time REAL,
            track TEXT NOT NULL,
            distance INTEGER,
            condition TEXT NOT NULL,
            description TEXT NOT NULL,
            main_inner_track_indicator TEXT NOT NULL,
            workouts_that_day_distance INTEGER,
            rank INTEGER,
            FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE
        );
        "#,
        r#"
        CREATE TABLE IF NOT EXISTS past_performances (
            id INTEGER PRIMARY KEY,
            horse_id INTEGER NOT NULL,
            race_date TEXT NOT NULL,
            days_since_last_race INTEGER,
            track_code TEXT NOT NULL,
            bris_track_code TEXT NOT NULL,
            race_number INTEGER,
            track_condition TEXT NOT NULL,
            distance INTEGER,
            surface TEXT NOT NULL,
            special_chute_indicator TEXT NOT NULL,
            entrants INTEGER,
            post_position INTEGER,
            equipment TEXT NOT NULL,
            racename TEXT NOT NULL,
            medication INTEGER,
            trip_comment TEXT NOT NULL,
            winners_name TEXT NOT NULL,
            place_name TEXT NOT NULL,
            show_name TEXT NOT NULL,
            winners_weight INTEGER,
            place_weight INTEGER,
            show_weight INTEGER,
            winners_margin REAL,
            place_margin REAL,
            show_margin REAL,
            alternate_comment_line TEXT NOT NULL,
            weight INTEGER,
            odds REAL,
            entry TEXT NOT NULL,
            race_classication TEXT NOT NULL,
            claiming_price INTEGER,
            purse INTEGER,
            start_call_position TEXT NOT NULL,
            first_call_position TEXT NOT NULL,
            second_call_position TEXT NOT NULL,
            gate_call_position TEXT NOT NULL,
            stretch_call_position TEXT NOT NULL,
            finish_position TEXT NOT NULL,
            money_position TEXT NOT NULL,
            start_call_between_lengths_leader REAL,
            start_call_between_lengths REAL,
            first_call_between_lengths_leader REAL,
            first_call_between_lengths REAL,
            second_call_between_lengths_leader REAL,
            second_call_between_lengths REAL,
            bris_race_shape_1st_call INTEGER,
            stretch_call_between_lengths_leader REAL,
            stretch_call_between_lengths REAL,
            finish_between_lengths_leader REAL,
            finish_between_lengths REAL,
            bris_race_shape_2nd_call INTEGER,
            bris_2f_pace INTEGER,
            bris_4f_pace INTEGER,
            bris_6f_pace INTEGER,
            bris_8f_pace INTEGER,
            bris_10f_pace INTEGER,
            bris_late_pace INTEGER,
            bris_speed_rating INTEGER,
            speed_rating INTEGER,
            track_variant INTEGER,
            two_f_fraction REAL,
            three_f_fraction REAL,
            four_f_fraction REAL,
            five_f_fraction REAL,
            six_f_fraction REAL,
            seven_f_fraction REAL,
            eight_f_fraction REAL,
            ten_f_fraction REAL,
            twelve_f_fraction REAL,
            fourteen_f_fraction REAL,
            sixteen_f_fraction REAL,
            fraction_1 REAL,
            fraction_2 REAL,
            fraction_3 REAL,
            final_time REAL,
            claimed_code TEXT NOT NULL,
            trainer TEXT NOT NULL,
            jockey TEXT NOT NULL,
            apprentice_weight_allowance INTEGER,
            race_type TEXT NOT NULL,
            age_sex_restrictions TEXT NOT NULL,
            statebred_flag TEXT NOT NULL,
            restricted_qualifier_flag TEXT NOT NULL,
            favorite_indicator TEXT NOT NULL,
            front_bandages_indicator TEXT NOT NULL,
            bris_speed_par_for_race INTEGER,
            bar_shoes TEXT NOT NULL,
            company_line_codes TEXT NOT NULL,
            low_claiming_price_of_race INTEGER,
            high_claiming_price_of_race INTEGER,
            code_for_prior_races TEXT NOT NULL,
            claimed_and_trainer_switches_1 TEXT NOT NULL,
            claimed_and_trainer_switches_2 TEXT NOT NULL,
            claimed_and_trainer_switches_3 TEXT NOT NULL,
            claimed_and_trainer_switches_4 TEXT NOT NULL,
            claimed_and_trainer_switches_5 TEXT NOT NULL,
            claimed_and_trainer_switches_6 TEXT NOT NULL,
            extended_start_comment TEXT NOT NULL,
            sealed_track_indicator TEXT NOT NULL,
            previous_all_weather_surface_indicator TEXT NOT NULL,
            equibase_abbreviated_race_condition TEXT NOT NULL,
            FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE
        );
        "#,
        r#"
        CREATE TABLE IF NOT EXISTS key_trainer_stats (
            id INTEGER PRIMARY KEY,
            horse_id INTEGER NOT NULL,
            category TEXT NOT NULL,
            starts INTEGER,
            win_pct REAL,
            in_the_money_pct REAL,
            roi REAL,
            FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE CASCADE
        );
        "#,
    ];

    for statement in statements {
        sqlx::query(statement).execute(pool).await?;
    }

    Ok(())
}